2025-06-08 22:25:09,993 ERROR: Exception on / [GET] [in /Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/core/routes.py", line 14, in dashboard
    return render_template('core/dashboard.html')
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/templates/core/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/templates/base.html", line 131, in top-level template code
    <a class="nav-link" href="{{ url_for('project.list') }}">
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'project.list'. Did you mean 'project.list_projects' instead?
2025-06-08 22:25:10,000 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/__init__.py:93]
2025-06-08 22:30:05,643 INFO: Application startup [in /Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/utils/logger.py:55]
2025-06-08 22:30:19,051 ERROR: Exception on / [GET] [in /Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/core/routes.py", line 14, in dashboard
    return render_template('core/dashboard.html')
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/templates/core/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/templates/base.html", line 144, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/templates/core/dashboard.html", line 101, in block 'content'
    <a href="{{ url_for('project.list') }}" class="btn btn-primary">View All Projects</a>
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'project.list'. Did you mean 'project.list_projects' instead?
2025-06-08 22:30:19,057 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/__init__.py:93]
2025-06-08 22:30:27,289 ERROR: Exception on /dashboard [GET] [in /Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/core/routes.py", line 14, in dashboard
    return render_template('core/dashboard.html')
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/templates/core/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/templates/base.html", line 144, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/templates/core/dashboard.html", line 101, in block 'content'
    <a href="{{ url_for('project.list') }}" class="btn btn-primary">View All Projects</a>
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/deveshmalu/Library/Python/3.9/lib/python/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'project.list'. Did you mean 'project.list_projects' instead?
2025-06-08 22:30:27,294 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/__init__.py:93]
2025-06-08 22:32:46,540 INFO: Application startup [in /Users/deveshmalu/HRMSV3/HRMSV3_optimized/app/utils/logger.py:55]
